export const BROWN_HISTORY = [
  { id: 106, date: "2026-02-10 14:57", content: "[정책] 파트너 관리 추가 수정: 파트너 정보 탭 전 필드 필수 입력, 리스트 컬럼 변경(파트너 ID/구분/하위 구분/파트너 이름/주소/법인명), 파트너 ID 내림차순 기본 정렬", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 105, date: "2026-02-10 14:30", content: "[정책] 파트너 관리 정보 구조 개편: 3개 카드 구조(기본 정보/주 연락처/사업자 정보), 주소→주소+상세 주소 분리, 삭제 버튼 추가(soft delete)", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 104, date: "2026-02-10 13:50", content: "[문서] 8개 화면 MD 명세 정합성 검증 및 개선: 발행 유형 정책(182→75줄), AI 모델 정책(구현↔MD 불일치 전면 재작성)", isPolicyChange: false, links: [{ label: "발행 유형 정책", page: "order-type-policy" }, { label: "AI 모델 정책", page: "ai-policy" }, { label: "존 정책", page: "zone-policy" }, { label: "존 배정", page: "zone-assignment" }, { label: "지역 정책", page: "regionpolicy" }, { label: "파트너 관리", page: "partners" }, { label: "파트너 담당자", page: "partner-managers" }, { label: "수행원 조회", page: "workers" }] },
  { id: 103, date: "2026-02-10 10:00", content: "[정책] 오더 취소 유형 재분류: 변경/미예약/노쇼/우천 취소를 '시스템 취소(*)' 접두어로 변경", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 102, date: "2026-02-09 19:00", content: "[문서] MD 명세 정합성 검증 및 개선: 7개 화면 JSX↔MD 비교 후 불일치 수정(대시보드 적시율/리드타임 컬럼 제거)", isPolicyChange: false, links: [{ label: "대시보드", page: "dashboard" }, { label: "오더 관리", page: "orders" }, { label: "합의 요청", page: "settlement" }, { label: "분실물 관리", page: "lostfound" }] },
  { id: 101, date: "2026-02-09 18:00", content: "[정책] 분실물 관리 연계 오더 ID 읽기 전용 전환, 분실물 정보 생성 흐름 명세(옥스트라 카드 기반/수행원 현장 발견 2가지 경로) 기술", isPolicyChange: true, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 100, date: "2026-02-09 17:00", content: "[정책] 분실물 관리 상태 전이 개편: 처리 상태 Select 제거→자동 전이(주소 저장 시)+액션 버튼([발송 완료]/[폐기 완료]) 방식", isPolicyChange: true, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 99, date: "2026-02-09 16:00", content: "[UI] 분실물 관리 스타일 통일: 공용 ui.jsx 컴포넌트 전환(로컬 인라인 228줄 제거), FilterPanel 적용(검색항목+검색어/파트너이름/처리상태/접수일 기간)", isPolicyChange: false, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 98, date: "2026-02-09 15:00", content: "[기능] 존 배정 관리 상세 고도화: 배정된 수행원 정보 영역 추가(수행원 ID/이름/벌점), 파트너 변경 시 Select 즉시 컨펌 방식(저장 버튼 제거)", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 97, date: "2026-02-09 14:00", content: "[UI] 수행원 조회 개편: 지역1/지역2 필터 및 컬럼 삭제, 배정된 쏘카존 컬럼→배정 존 개수로 변경, 상세 화면 배정 지역 영역 제거", isPolicyChange: false, links: [{ label: "수행원 조회", page: "workers" }] },
  { id: 96, date: "2026-02-09 13:00", content: "[정책] 분실물 관리 고도화: 인라인 편집 구조(수정 모드 제거, Select 컨펌, Input 개별 저장), 구분별 상태 흐름 분리(일반/귀중품)", isPolicyChange: true, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 95, date: "2026-02-09 11:14", content: "[UI] 리스트-상세 필드 정합성 보완: 오더 관리 상세에 차량 ID 추가, 미션 정책 상세에 등록일시/진행률 추가, 수행원 상세에 배정 지역(지역1/지역2) 추가", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }, { label: "미션 관리", page: "missions" }, { label: "수행원 조회", page: "workers" }] },
  { id: 94, date: "2026-02-09 11:07", content: "[UI] 오더 관리 취소 유형 필터 항상 표시: 진행 상태 '취소' 선택 전까지 비활성화(회색 처리), 취소 선택 시 활성화", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 93, date: "2026-02-09 10:25", content: "[UI] 존 정책 관리 차량 대수 필드 추가: 리스트 및 상세 화면에 존별 차량 대수 표시", isPolicyChange: false, links: [{ label: "존 정책 관리", page: "zone-policy" }] },
  { id: 92, date: "2026-02-09 09:50", content: "[정책] 수행원 조회 벌점 시스템: 수행 점수→벌점으로 변경, 목업 데이터 10명으로 증가, 벌점 이력(지연/노쇼) 추가, 오더 ID 클릭 시 새 탭 이동", isPolicyChange: true, links: [{ label: "수행원 조회", page: "workers" }] },
  { id: 91, date: "2026-02-06 18:30", content: "[리팩토링] 조회 조건 설정(FilterPanel) 공통 컴포넌트화: 9개 페이지 필터 UI 통일, 로컬 UI 컴포넌트 공용화, 칩(Chip) 표시 및 설정 초기화 버튼 전체 적용", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }, { label: "차량 관리", page: "cars" }, { label: "미션 관리", page: "missions" }, { label: "청구 관리", page: "billing" }, { label: "합의 요청 관리", page: "settlement" }, { label: "존 정책 관리", page: "zone-policy" }, { label: "존 배정 관리", page: "zone-assignment" }, { label: "파트너 담당자 관리", page: "partner-managers" }, { label: "수행원 조회", page: "workers" }] },
  { id: 90, date: "2026-02-06 17:30", content: "[UI] 합의 요청 관리: 필터 적용 정보 칩(Chip) 표시 및 필터 초기화 버튼 추가", isPolicyChange: false, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 89, date: "2026-02-06 17:00", content: "[용어] 합의 요청 관리: 상태 용어 변경 - '수락'→'승인', '거절'→'반려' (기능/목업/명세서 전체 반영)", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 88, date: "2026-02-06 16:00", content: "[정책] 합의 요청 관리 고도화: 2단계 승인 처리자 1차/2차 분리(파트너 담당자/인터널 담당자), 검색 필터 추가(파트너 이름, 요청 유형, 요청일 기간), 필터 배치 순서 변경", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 87, date: "2026-02-06 14:00", content: "[정책] 청구 관리 고도화: 리스트에 오더 구분/발행 유형/세차 유형/파트너 유형 컬럼 추가, 정산 제외 기능(필터/컬럼/상세 필드/토글 버튼)", isPolicyChange: true, links: [{ label: "청구 관리", page: "billing" }] },
  { id: 86, date: "2026-02-06 12:00", content: "[정책] 미션 정책 관리 상세 보완: 비활성 전환 시 대기 차량 일괄 삭제 정책, 차량 개별 삭제 컨펌, 정책 삭제 컨펌 메시지 변경, 읽기 전용 필드 Disabled UI 스타일 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 85, date: "2026-02-06 11:00", content: "[정책] 미션 정책 관리 고도화: 등록 후 상태만 변경 가능(나머지 읽기 전용), 상태 변경 컨펌, 정책 삭제 조건부 활성화(할당 차량 유무)", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 84, date: "2026-02-06 09:40", content: "[정책] 청구 관리 고도화: 기본 필터 최근 1개월로 변경, 상세 화면에 오더 정보(수행 일시/차량/세차 유형 등) 및 세차 수행 사진 추가", isPolicyChange: true, links: [{ label: "청구 관리", page: "billing" }] },
  { id: 83, date: "2026-02-05 17:00", content: "[UI] LNB 메뉴 구조 변경: '존 배정 관리'를 '오더 정책 관리' 그룹으로 이동, 메뉴 그룹 순서 재정렬 (업무 관리 → 오더 정책 관리 → 정보 관리)", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 82, date: "2026-02-05 16:00", content: "[UI] 합의 요청 관리: '처리자' → '처리 주체'로 변경, 인터널/파트너 배지 표시, 상세 화면에 처리 주체 필드 추가", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 81, date: "2026-02-05 15:40", content: "[UI] 합의 요청 관리: '요청 시간' → '요청 일시' 문구 변경, 상세 화면에서 '요청 사유', '세차 항목' 필드 제거", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 80, date: "2026-02-05 15:30", content: "[기능] 합의 요청 관리: 처리자/처리 일시 필드 추가, 합의 유형별 처리자 정책 적용 (1단계: 내부/파트너 관리자, 2단계: 내부 관리자만)", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 79, date: "2026-02-05 15:10", content: "[UI] 차량 관리: 리스트에서 '파트너 이름', '발행된 오더' 컬럼 제거 (기술 제약), 파트너 필터 유지, 상세 화면 발행된 오더 링크 추가", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 78, date: "2026-02-03 18:30", content: "[기능] 대량 존 배정: CSV 파일 업로드를 통한 존-파트너 일괄 배정, 드래그앤드롭 업로드, 양식 다운로드, 검증 실패 내역 표시", isPolicyChange: true, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 77, date: "2026-02-03 17:00", content: "[기능] 파트너 단가 정책 일자별 관리: 적용 시작일 지정, 적용 중/예정 정책 분리 표시, 미래 적용 정책 사전 등록 기능", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 73, date: "2026-02-03 11:30", content: "[기능] 존 배정 관리 메뉴 신설: 존 중심 파트너 배정 현황 관리, 미배정 존 식별 UI, 파트너 관리에서 존 배정 탭 분리", isPolicyChange: true, links: [{ label: "존 배정 관리", page: "zone-assignment" }, { label: "파트너 관리", page: "partners" }] },
  { id: 72, date: "2026-02-02 18:15", content: "[정책] 합의 요청 관리: 요청 유형 값 형식 변경 - 변경 내용 명시적 표시 (예: 현장 변경(내부→내외부), 전환(현장→입고), 입고 변경(내외부→특수))", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 71, date: "2026-02-02 15:05", content: "[기능] 핸들러 오더 고도화: 파트너 이름 '핸들러' 고정, 사진 및 점검 탭 추가 (진행 이력/탁송 상태 연계, 세차 전후 사진, 세차 후기)", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 70, date: "2026-02-02 11:12", content: "[기능] 핸들러 파트너 유형 오더 지원: 기계세차 오더 조회, 파트너 유형별 탭/금액 정보 조건부 표시, 미션핸들 예약 정보 카드 추가", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 69, date: "2026-01-28 23:12", content: "[기능] 오더 관리 고도화: 분실물 상세 표시, 오더 삭제→취소로 변경, 입고 파트너 탁송 정보 추가, 검색 기준 용어 수정", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 68, date: "2026-01-28 18:27", content: "[정책] 오더 상태 전이 정책 개편: 파트너 유형 무관 통일된 4단계 흐름 (발행→예약→수행 중→완료) 적용", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 67, date: "2026-01-28 10:13", content: "[문서] 오더 관리 기능 명세서 고도화: 운영 시나리오 구체화, 점검 항목 전체 목록", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 66, date: "2026-01-26 16:45", content: "미션 정책 관리 - 할당된 차량 검색 기능 및 목업 데이터 추가", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 65, date: "2026-01-23 17:09", content: "오더 관리 목업 데이터 외부 파일 분리 및 200개로 증량, 필터 기본값 1개월로 변경", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 64, date: "2026-01-23 14:06", content: "[기능] 미션 관리 - 상태(활성/비활성) 추가", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 63, date: "2026-01-23 13:26", content: "[정책] 미션 관리 기능 정책 변경", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 62, date: "2026-01-23 11:15", content: "[정책] 오더별 수행 목업, 발행 유형별 수행(사진 촬영, 점검) 기능명세 작성", isPolicyChange: true, links: [{ label: "오더별 수행 목업", page: "checklist-mockup" }] },
  { id: 61, date: "2026-01-20 14:30", content: "[기능] 분실물 관리: 검색/필터, UI 일관성 및 상세화면 동작 개선", isPolicyChange: true, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 60, date: "2026-01-20 11:12", content: "[기능] 관제 대시보드 구현 방향 안내 모달 레이어 추가", isPolicyChange: false, links: [] },
  { id: 59, date: "2026-01-20 09:30", content: "[기능] URL 쿼리 스트링 양방향 동기화 적용 및 페이지별 피드백 로딩 로직 고도화 (Deep Linking 지원)", isPolicyChange: false, links: [] },
  { id: 58, date: "2026-01-19 17:30", content: "[UI] 대시보드 문구 및 노출 필요한 정보 요소 변경", isPolicyChange: true, links: [{ label: "대시보드", page: "dashboard" }] },
  { id: 57, date: "2026-01-19 17:30", content: "[고도화] 피드백 작성자 정보 상시 노출, 해결 컨펌 추가", isPolicyChange: false, links: [] },
  { id: 56, date: "2026-01-19 12:28", content: "[기능] QnA 댓글(피드백) 입력 기능 추가", isPolicyChange: true, links: [] },
  { id: 55, date: "2026-01-16 13:04", content: "[UI/UX] 주요 Drawer 하이브리드 레이아웃 적용: 데스크톱 너비 조절 기능 복구 및 모바일 반응형 최적화", isPolicyChange: false, links: [] },
  { id: 54, date: "2026-01-16 12:23", content: "[리팩토링] App.jsx 비대화 해결 완료: 모든 페이지 분리", isPolicyChange: false, links: [] },
  { id: 53, date: "2026-01-16 12:10", content: "[UI/UX] 오더 관리: 상세 Drawer 내 지역(지역1, 2) 및 일시(발행, 수행) 정보 추가", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 52, date: "2026-01-16 11:45", content: "[기능/UI] 오더 관리: 검색 필터 레이블 개선 및 테이블 컬럼 확장 (지역, 일시 정보 추가)", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 51, date: "2026-01-15 22:14", content: "[기능] 오더 수동 발행 기능 고도화: 차량 번호 유효성 체크 및 차량 기본정보 조회", isPolicyChange: true, links:  [{ label: "오더 관리", page: "orders" }] },
  { id: 50, date: "2026-01-15 21:59", content: "[기능] 오더 수동 발행 기능 고도화: 발행 옵션(오더 구분/유형) 선택 기능 추가", isPolicyChange: true, links:  [{ label: "오더 관리", page: "orders" }] },
  { id: 49, date: "2026-01-15 21:20", content: "[버그수정] 모바일 브라우저 초기 DIM 중첩 현상 해결 및 레이아웃 z-index 최적화", isPolicyChange: false, links: [] },
  { id: 48, date: "2026-01-15 18:27", content: "[Hotfix] 검색 필터 UI 스타일 충돌 수정: Select/Input 너비 강제 적용 (!important)", isPolicyChange: false, links: [] },
  { id: 47, date: "2026-01-15 18:25", content: "[UI/버그수정] 검색 필터 레이아웃 중첩 문제 해결 및 카테고리별 검색 UI 정교화", isPolicyChange: false, links: [] },
  { id: 46, date: "2026-01-15 18:23", content: "[시스템] 담당자 정보 간소화(상태 제거/삭제 추가), CMS 외부 링크 연동 및 청구서 엑셀 다운로드 기능 추가", isPolicyChange: false, links: [{ label: "담당자 조회", page: "partner-managers" }, { label: "청구 관리", page: "billing" }] },
  { id: 45, date: "2026-01-15 18:20", content: "[정책] 단가 관리 기능을 파트너 상세 정보로 통합 및 CRUD 기능 구현", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 44, date: "2026-01-15 18:17", content: "[고도화] 미션 관리: 일괄 삭제 시 사유 입력 모달 적용 (Audit Log 강화)", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 43, date: "2026-01-15 18:14", content: "[기능] 미션 관리: 미션 일괄 선택 삭제 기능 도입", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 42, date: "2026-01-15 18:10", content: "[UI] 검색 카테고리 필터 도입 및 테이블 정렬 기능 전사 적용", isPolicyChange: false, links: [] },
  { id: 41, date: "2026-01-15 18:09", content: "[고도화] 검색 UI 표준화, 단가 정책 파트너 통합 및 미션 벌크 삭제 기능 도입", isPolicyChange: false, links: [] },
  { id: 40, date: "2026-01-15 15:20", content: "[Hotfix] 파트너 관리 페이지 파일 누락 수정 (PartnersPage.jsx 생성)", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 39, date: "2026-01-15 15:15", content: "[버그수정] 파트너 관리 컴포넌트 경로 정상화 및 신규 재구현 기능 UI 연동 완료", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 38, date: "2026-01-15 15:06", content: "[기능] 파트너 관리 고도화: 필드 명칭 표준화(파트너 이름) 및 신규 등록/수정 기능 구현, UI 불필요 항목 제거", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 37, date: "2026-01-15 14:53", content: "[기능] 파트너 관리 재구현: 상세 계약 정보 및 대규모 존 배정(지역정보 병기) 기능 적용", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 36, date: "2026-01-15 14:38", content: "[기능] 담당자/수행원 조회: 파트너사별 인력 현황 및 존 배정 모니터링 기능 구현", isPolicyChange: false, links: [{ label: "담당자 조회", page: "partner-managers" }, { label: "수행원 조회", page: "workers" }] },
  { id: 35, date: "2026-01-15 14:36", content: "[기능] 파트너 관리: 파트너사 등록/수정 및 복수 지역(Zone) 할당 로직 구현", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 34, date: "2026-01-15 14:32", content: "[UI] LNB 메뉴 그룹 동작 표준화: 오더 정책 및 업무 관리 그룹 아코디언 기능 적용", isPolicyChange: false, links: [] },
  { id: 33, date: "2026-01-15 14:15", content: "[UI] 사이드바(LNB) 내부 스크롤 적용 및 스크롤바 UI 숨김 처리", isPolicyChange: false, links: [] },
  { id: 32, date: "2026-01-15 13:30", content: "[UI] Drawer 닫기 버튼 스타일 조정: 배경 제거 및 Hover 효과 유지", isPolicyChange: false, links: [] },
  { id: 31, date: "2026-01-15 13:25", content: "[UI] 업데이트 이력 내 '제품 정책 변경' 건 선별 필터 기능 추가", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 30, date: "2026-01-15 13:20", content: "[시스템] 빌드 파이프라인 최적화: prebuild 스크립트를 통한 version.json 자동 갱신 로직 적용", isPolicyChange: false, links: [] },
  { id: 29, date: "2026-01-15 13:10", content: "[시스템] 전사 리스트 화면 페이지네이션(40개 단위) 도입 및 데이터 로딩 최적화", isPolicyChange: false, links: [] },
  { id: 28, date: "2026-01-15 13:05", content: "[정책] 미션별 금액 산정 기능 도입 및 수행 증빙 사진 필수 옵션 기본값 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 27, date: "2026-01-15 12:15", content: "[시스템] 업데이트 이력 관리 이원화(브라운/아스티) 및 외부 파일 연동, 버전 체크 로직 최적화", isPolicyChange: true, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 26, date: "2026-01-15 09:15", content: "[시스템] 모바일 반응형 레이아웃 대응: 햄버거 메뉴 및 사이드바 드로어 구현", isPolicyChange: false, links: [] },
  { id: 25, date: "2026-01-15 09:10", content: "[시스템] Vercel 트랜잭션 최적화: 업무시간 외 체크 제한 및 활동 기반 버전 업데이트 로직 고도화", isPolicyChange: false, links: [] },
  { id: 24, date: "2026-01-15 08:50", content: "[시스템] 실시간 버전 업데이트 감지 및 브라우저 캐시 무효화 기능 구현", isPolicyChange: false, links: [] },
  { id: 23, date: "2026-01-14 18:10", content: "미션 상세 화면 내 수행 증빙 사진 필수 여부 정보 노출", isPolicyChange: false, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 22, date: "2026-01-14 18:00", content: "[정책] 미션 등록 시 차량 번호 일괄 입력(최대 1,000건) 및 수행 증빙 사진 촬영 옵션 도입", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 21, date: "2026-01-14 17:40", content: "[정책] 미션 관리 내 차량 상세 정보(차종/지역) 연동 및 다차원 필터링 기능 강화", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 20, date: "2026-01-14 16:30", content: "[정책] 세차 유형 옵션 정렬 기준 변경(내외부 우선) 및 미사용 옵션(물세차) 제거", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 19, date: "2026-01-14 16:25", content: "[정책] LNB 메뉴 순서 변경(미션 관리 하향 조정) 및 수행완료 미션 삭제 제한 정책 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 18, date: "2026-01-14 16:16", content: "[정책] 필드 순서 표준화(오더 구분/유형/세차 유형) 및 미션-오더 연동 상세 로직 고도화", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 17, date: "2026-01-14 16:01", content: "업데이트 이력 시간 기록 규칙 확정 (KST 16:01 기준) 및 기존 이력 시간 교정", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 16, date: "2026-01-14 15:50", content: "[정책] 관리자-수행원 간 정보 관심사 분리 정책에 따라 어드민 내 현장 가이드 및 유종 정보 전면 제거", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 15, date: "2026-01-14 15:40", content: "[정책] 세차 업무 무관 정보(유종) 제거 및 충전보장형 차량 대상 특수 반납 가이드 노출 정책 적용", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 14, date: "2026-01-14 15:25", content: "[정책] 세차 대상 차량 기준(sharing_type) 정의 및 진행중 오더의 실시간 상태 노출 로직 적용", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 13, date: "2026-01-14 15:10", content: "[정책] 업데이트 이력 관리 체계 개편: 제품 정책 변경 여부 식별 및 기록 의무화", isPolicyChange: true, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 12, date: "2026-01-14 14:50", content: "디자인 가이드(PNG) 분석 기반 UI 컴포넌트 스타일 고도화 및 디자인 토큰 반영", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 11, date: "2026-01-14 14:35", content: "업데이트 이력 자동 기록 규칙 최종 수정 (실시간 KST 반영) 및 UI 점검", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 10, date: "2026-01-14 14:30", content: "업데이트 이력 데이터 구조 개선(링크 추가) 및 UI 컬럼 반영", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 9, date: "2026-01-13 18:40", content: "[정책] 미션 삭제 시 사유 입력 강제 및 감사 로그 기록 정책 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 8, date: "2026-01-13 18:25", content: "[정책] 세차 오더-미션 간 상태 라이프사이클 동기화 로직 정의", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 7, date: "2026-01-13 18:15", content: "[정책] 파트너 유형별(현장/입고) 프로세스 분리에 따른 진행 상태 선택값 제한 규칙 적용", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 6, date: "2026-01-13 18:10", content: "차량 상세 내 모든 세차 이력 항목에 대해 오더 상세 Drawer 자동 연결 기능 보완", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 5, date: "2026-01-13 17:55", content: "차량 상세 세차 이력 클릭 시 새 창에서 오더 상세 자동 연결 기능 구현", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 4, date: "2026-01-13 17:37", content: "업데이트 이력 페이지 UI 개선 (헤더 명칭 변경) 및 자동 기록 규칙 적용", isPolicyChange: false, links: [] },
  { id: 3, date: "2026-01-13 17:25", content: "업데이트 이력 ID 컬럼 추가 및 정렬, 사이드바 스크롤바 숨김 처리", isPolicyChange: false, links: [] },
  { id: 2, date: "2026-01-13 16:57", content: "전체 용어 및 데이터 표기 형식 표준화 (차량 번호, 존 이름, 파트너 이름 등)", isPolicyChange: false, links: [] },
  { id: 1, date: "2026-01-13 15:53", content: "기능 명세(Markdown) Drawer 연동 및 렌더러 구현", isPolicyChange: false, links: [] },
];

export const PARTNER_HISTORY = [
  { id: 4, date: "2026-02-26 17:07", content: "파트너 오더 관리: '오더 조회'→'오더 관리' 명칭 변경, 오더 할당 기능 추가 — 발행 상태 오더에 존 담당 수행원 배정 및 예약 (3단계 플로우: 수행원 선택→스케줄/차량 확인→시간 선택→할당 확정)", isPolicyChange: false, links: [{ label: "파트너 오더 관리", page: "partner-orders" }] },
  { id: 3, date: "2026-02-26 13:47", content: "파트너 대시보드·오더 조회: 기능명세(MD) 작성 — 인터널 대비 차이점 표, 영역/필터/컬럼/Drawer 구성 상세 기술", isPolicyChange: false, links: [{ label: "파트너 대시보드", page: "partner-dashboard" }, { label: "파트너 오더 조회", page: "partner-orders" }] },
  { id: 2, date: "2026-02-25 17:07", content: "파트너 오더 조회: 인터널 오더관리 기반 읽기전용 페이지 구축 (파트너 이름/유형 컬럼·필터 제외, 발행·완료·취소 버튼 제거, 대시보드 연동 필터)", isPolicyChange: false, links: [{ label: "파트너 오더 조회", page: "partner-orders" }] },
  { id: 1, date: "2026-02-25 16:36", content: "파트너 대시보드: 인터널 대시보드 기반 구축 (오더 현황, 리스크 관리, 시계열 차트), 강남모빌리티 데이터 필터링, 파트너 수행관리 섹션 제거", isPolicyChange: false, links: [{ label: "파트너 대시보드", page: "partner-dashboard" }] },
];

export const ASTI_HISTORY = [
  { id: 54, date: "2026-03-03 18:26", content: "합의 요청 관리: 요청 유형 4개 대분류 재구성(현장 변경/전환/입고 변경/추가 미션), 변경 전·후 세차유형 컬럼 추가, 자동 승인·사후 반려 정책 반영 — 인터널/파트너 어드민 및 PRD 일괄 적용", isPolicyChange: true, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 53, date: "2026-03-03 17:00", content: "오더 관리: 수동 발행 시 오더 구분(수시)/발행유형(수시세차) 고정 — Select 비활성화 처리, PRD 반영", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 52, date: "2026-02-27 18:20", content: "합의 요청 관리: 파트너 어드민 합의 요청 관리 페이지 구축", isPolicyChange: false, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 51, date: "2026-02-27 18:04", content: "청구 관리: 파트너 어드민 청구 관리 페이지 구축", isPolicyChange: false, links: [{ label: "청구 관리", page: "billing" }] },
  { id: 50, date: "2026-02-27 17:51", content: "분실물 관리: 분실물 구분(일반/귀중품) 필드 삭제 — 목업 데이터, 인터널/파트너 어드민 화면, 기능명세 일괄 반영", isPolicyChange: false, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 49, date: "2026-02-27 16:16", content: "파트너 분실물 관리: 등록 모달 개선 — 차량 번호→세차 오더 번호 검색/선택 방식 변경, 처리 상태 선택 추가", isPolicyChange: false, links: [{ label: "파트너 분실물 관리", page: "partner-lostfound" }] },
  { id: 48, date: "2026-02-27 16:12", content: "파트너 분실물 관리: 분실물 등록 기능 추가 (차량 선택, 존 정보 자동 표시, 분실물 구분/상세 입력)", isPolicyChange: false, links: [{ label: "파트너 분실물 관리", page: "partner-lostfound" }] },
  { id: 47, date: "2026-02-27 16:03", content: "파트너 분실물 관리: 페이지 구축 (인터널 기반, 파트너 이름 필터/컬럼/Drawer 필드 제거, 자사 데이터만 표시)", isPolicyChange: false, links: [{ label: "파트너 분실물 관리", page: "partner-lostfound" }] },
  { id: 46, date: "2026-02-27 15:54", content: "분실물 관리: 처리상태 변경이력 탭 추가 (변경 계정, 변경 일시 기록)", isPolicyChange: false, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 45, date: "2026-02-27 14:19", content: "차량 관리: 차량 상세 Drawer에 존 유형 필드 추가", isPolicyChange: false, links: [{ label: "차량 관리", page: "cars" }] },
  { id: 44, date: "2026-02-27 14:17", content: "차량 관리: 존 유형 필드 추가 (목업 데이터, 리스트 컬럼, 조회 조건 필터)", isPolicyChange: false, links: [{ label: "차량 관리", page: "cars" }] },
  { id: 43, date: "2026-02-27 12:10", content: "차량 관리: 파트너 이름을 현장 파트너/입고 파트너로 분리 (필터, Drawer, 목업 데이터)", isPolicyChange: false, links: [{ label: "차량 관리", page: "cars" }] },
  { id: 42, date: "2026-02-26 15:18", content: "오더 상세 Drawer 개편: 헤더를 차량번호(차종)+진행상태로 변경, 기본정보 카드를 오더정보·차량정보 2개 카드로 분리, 파트너 이름 필드 추가 (인터널+파트너 어드민 동시 적용)", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }, { label: "파트너 오더 조회", page: "partner-orders" }] },
  { id: 38, date: "2026-02-25 16:54", content: "목업데이터: 강남모빌리티(P-001) 데이터 보강 — 차량(3→8), 청구(7→15), 합의요청(7→10), 분실물(0→10, 파트너명 실명 전환), 배송정보(0→15), 수행원정보(0→12)", isPolicyChange: false, links: [] },
  { id: 36, date: "2026-02-25 10:16", content: "존 배정 관리: 수행원 목업 데이터 확장(10→14명) — 모든 존에 현장/입고 수행원 최소 1명씩 배정되도록 zoneIds 전수 커버", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 35, date: "2026-02-25 09:59", content: "수행원 조회: 파트너 이름을 파트너 관리 기준으로 변경(강남모빌리티/미션핸들코리아/수원카케어), 파트너 유형 컬럼 및 상세 필드 추가", isPolicyChange: false, links: [{ label: "수행원 조회", page: "workers" }] },
  { id: 34, date: "2026-02-25 09:43", content: "존 배정 관리: 필드명 변경 — '현장세차 파트너'→'현장 파트너', '입고세차 파트너'→'입고 파트너' (리스트/필터/드로워/해제 팝업/대량 배정 전체 반영)", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 33, date: "2026-02-25 09:38", content: "존 배정 관리: 목업 파트너 데이터를 파트너 관리 기준으로 변경 — 현장세차(강남모빌리티/미션핸들코리아), 입고세차(수원카케어)", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }, { label: "파트너 관리", page: "partners" }] },
  { id: 32, date: "2026-02-25 09:35", content: "존 배정 관리: 상세 드로워 '파트너 배정' 섹션 이름을 '배정된 파트너'로 변경", isPolicyChange: false, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 31, date: "2026-02-25 09:33", content: "파트너 관리: '구분' 컬럼 삭제, 상세 기본 정보에서 '파트너 구분' 필드 제거", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 30, date: "2026-02-25 09:30", content: "파트너 관리: '하위 구분'→'파트너 유형', '현장 세차장'→'현장 파트너', '입고 세차장'→'입고 파트너'로 용어 변경", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 29, date: "2026-02-25 08:55", content: "분실물 관리: 수정 모드에서 처리 상태 Select 추가 — 구분(일반/귀중품)별 유효 상태 목록에서 직접 변경 가능", isPolicyChange: false, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 28, date: "2026-02-25 08:50", content: "분실물 관리: 테이블에 수정 아이콘(Pencil) 컬럼 추가 — 종결 상태가 아닌 행에 수정 아이콘 표시, 클릭 시 수정 모드로 Drawer 열림", isPolicyChange: false, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 27, date: "2026-02-25 08:24", content: "차량 관리: 지역2 필터를 검색+필터 조합(SearchableSelect)으로 변경 — 텍스트 입력으로 옵션 검색 후 드롭다운에서 선택 가능", isPolicyChange: false, links: [{ label: "차량 관리", page: "cars" }] },
  { id: 26, date: "2026-02-24 18:50", content: "합의 요청 관리: 목업 데이터 전면 교체 — 오더 관리의 시스템(변경 취소) 오더 5건 기반 + 추가 데이터로 8가지 요청 유형 전수 커버(12건), 파트너 이름 실데이터 연동(강남모빌리티/수원카케어)", isPolicyChange: false, links: [{ label: "합의 요청 관리", page: "settlement" }] },
  { id: 25, date: "2026-02-24 18:25", content: "미션 정책 관리, 합의 요청 관리: 날짜 필터 UI 통일 — 개별 시작/종료 필드를 '일시' 한 행(시작 ~ 종료) 형식으로 변경, 미션 정책 관리에 미션 제목 검색 추가", isPolicyChange: false, links: [{ label: "미션 정책 관리", page: "missions" }, { label: "합의 요청 관리", page: "settlement" }] },
  { id: 24, date: "2026-02-24 18:00", content: "오더 관리: 필터 UI 개선 — 기본 필터 4개(차량번호/세차유형/진행상태/발행일시) 1줄 노출 + 상세 필터 10개 '필터 추가' 버튼으로 온디맨드 추가, 적용 필터 칩 표시, 진행상태 연동 자동 필터 추가(취소→취소유형, 완료→지연여부)", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 23, date: "2026-02-24 16:58", content: "대시보드: 데이터 소스 전환 (dashboard.json 삭제 → orders.json + orders-leadTime.json 기반 실시간 산출), 취소 카드 동적 유형 표시, 지연 판정 leadTime 기반으로 변경", isPolicyChange: false, links: [{ label: "대시보드", page: "dashboard" }] },
  { id: 22, date: "2026-02-24 16:33", content: "벌점 정책 변경: 지연→미예약으로 변경 (24시간 미예약 시 담당 존 파트너 전체 수행원에게 벌점 부과)", isPolicyChange: true, links: [{ label: "수행원 조회", page: "workers" }, { label: "오더 관리", page: "orders" }] },
  { id: 21, date: "2026-02-24 16:11", content: "오더 관리: 오더 체인 타임라인 UI 구현 (취소→재발행 플로우 시각화, 참조 오더별 발행·취소 시각/귀책·면책 표시, 산출 요약 박스)", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 20, date: "2026-02-24 15:56", content: "오더 정책: 리드타임·귀책 소요시간·면책 시간·지연 처리 정책 정의 (귀책 소요시간 > 72h 지연 판정, 벌점 연동)", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 19, date: "2026-02-24 15:56", content: "오더 정책: 취소 유형 재정의 (5→9개 유형, 귀책/면책 구분 추가, 취소 주체·대상 명시, 유형별 정책 상세 기술)", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 18, date: "2026-02-24 15:50", content: "오더 관리: 리스트에 지연 여부 컬럼 추가 (완료 오더만 지연/정상 배지 표시)", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 17, date: "2026-02-24 15:45", content: "오더 관리: 데이터 건수 표시 추가 (필터된 결과 N건 / 전체 M건), 지연 완료 오더 필터 추가", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 16, date: "2026-02-24 15:30", content: "오더 관리: 목데이터 200건 확장 (완료 100/수행중 20/예약 50/취소 30), 기본 정렬 발행 일시 내림차순으로 변경, 목데이터 JSON 분리", isPolicyChange: false, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 15, date: "2026-02-23 16:47", content: "존배정관리: 배정 구조 변경 (단일 파트너 → 현장세차/입고세차 듀얼 파트너 배정)", isPolicyChange: true, links: [{ label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 14, date: "2026-02-23 12:13", content: "존정책관리: 일괄 수정 UX 변경 (필터 기반→체크박스 선택 기반, 버튼 위치/스타일 변경, 적용 전 확인 모달 추가)", isPolicyChange: false, links: [{ label: "존 정책 관리", page: "zone-policy" }] },
  { id: 13, date: "2026-02-23 11:43", content: "지역정책관리: 지역2정책 체크박스 클릭 시 Drawer 열림 방지, 일괄 수정 시 변경 확인 모달 추가", isPolicyChange: false, links: [{ label: "지역 정책 관리", page: "regionpolicy" }] },
  { id: 12, date: "2026-02-20 18:14", content: "발행유형정책, 존정책관리, 존배정관리: 수정/삭제 UX 변경 (인라인 아이콘, Drawer 상세↔수정, SaveConfirmModal, DeleteConfirmModal)", isPolicyChange: false, links: [{ label: "발행 유형 정책", page: "order-type-policy" }, { label: "존 정책 관리", page: "zone-policy" }, { label: "존 배정 관리", page: "zone-assignment" }] },
  { id: 11, date: "2026-02-20 17:42", content: "지역정책관리: 지역1/지역2 정책 수정 시 변경 내용 확인 팝업(SaveConfirmModal) 추가", isPolicyChange: false, links: [{ label: "지역 정책 관리", page: "regionpolicy" }] },
  { id: 10, date: "2026-02-20 17:21", content: "지역정책관리: 지역1 정책탭 수정UX 변경 (인라인→Drawer 기반 상세/수정)", isPolicyChange: false, links: [{ label: "지역 정책 관리", page: "regionpolicy" }] },
  { id: 9, date: "2026-02-20 14:30", content: "지역정책관리: 수정, 삭제 UX 변경", isPolicyChange: false, links: [{ label: "지역 정책 관리", page: "regionpolicy" }] },
  { id: 8, date: "2026-02-20 12:10", content: "발행유형정책: 기능명세 현행화 (존유형 점수, 탭순서, Drawer 구조, 부가 정책 필드, 설명/메모, 컬럼 테이블, 유효성 검사, Drawer 제목/Footer)", isPolicyChange: false, links: [{ label: "발행 유형 정책", page: "order-type-policy" }] },
  { id: 7, date: "2026-02-20 12:10", content: "발행유형정책: O/X 값 Y/N으로 통일", isPolicyChange: true, links: [{ label: "발행 유형 정책", page: "order-type-policy" }] },
  { id: 6, date: "2026-02-20 11:23", content: "존정책 관리: 라이트세차 Y/N 필터 추가", isPolicyChange: false, links: [{ label: "존정책 관리", page: "zone-policy" }] },
  { id: 5, date: "2026-02-20 11:15", content: "존정책 관리: '세차관리' Y/N 필드 추가 (존 단위 속성, 필터/상세/일괄수정 지원)", isPolicyChange: true, links: [{ label: "존정책 관리", page: "zone-policy" }] },
  { id: 4, date: "2026-02-19 18:09", content: "존정책 관리: 상세 화면 라이트세차 표기 Y/N으로 통일 (기존 true/false)", isPolicyChange: false, links: [{ label: "존정책 관리", page: "zone-policy" }] },
  { id: 3, date: "2026-02-19 18:09", content: "존정책 관리: 라이트세차/주기세차 '상위 정책 따름' 옵션 추가 (존정책 미설정 시 지역2→지역1 순 fallback)", isPolicyChange: true, links: [{ label: "존정책 관리", page: "zone-policy" }] },
  { id: 2, date: "2026-02-19 18:09", content: "존정책 관리: 상세 Drawer 저장 후 닫힘 방지, 저장 완료 alert 제거", isPolicyChange: false, links: [{ label: "존정책 관리", page: "zone-policy" }] },
  { id: 1, date: "2026-02-19 17:35", content: "존정책 관리: 정책유형 한글로 변경 (Zone→존정책, Region1→지역1정책, Region2→지역2정책)", isPolicyChange: false, links: [{ label: "존정책 관리", page: "zone-policy" }] },
];